### ISSUE TITLE
Request for publication information 

### ISSUE THREAD

**Issue by deleepa** [LasseRegin/medical-question-answer-data#1]
Hi. I'm part of a team that is currently attempting to use your dataset in a deep learning project. We need to do an accuracy comparison against our work and any previous work that has been done with this dataset before. Could you please let me know if you have any knowledge of any previous researches that have used any of these datasets?

**Comment by LasseRegin** [comment]
The only work that I know of is my own Master Thesis:

https://github.com/LasseRegin/master-thesis-deep-learning

Regards

Den 20. sep. 2017 4.34 PM skrev "Deleepa" <notifications@github.com>:

**Comment by deleepa** [comment]
Thank you!
